version: 2
jobs:
  build:
    working_directory: ~/app
    orbs:
      codecov: codecov/codecov
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: save-lcov-coverage
          command: 'npm run save-lcov-coverage'
      - codecov/upload:
          file: {{ coverage_report_filepath }}
      - store_artifacts:
          path: lcov_coverage